var robot = require("robotjs");

//literally a shitty spam function with robot.js

robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
robot.typeString("spam");
robot.keyTap("enter");
